{% set data = load_setup_py_data() %}

package:
  name: photodiag_web
  version: {{ data['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  entry_points:
    - photodiag_web = photodiag_web.cli:main

requirements:
  build:
    - python >=3.8
    - setuptools
  run:
    - python >=3.8
    - scipy
    - bokeh =3
    - bsread
    - pyepics
    - cam_server_client
    - uncertainties
    - elog >=1.3.16
    - selenium
    - geckodriver
    - firefox

about:
  home: https://github.com/paulscherrerinstitute/photodiag_web
  summary: {{ data['description'] }}
  license: GNU GPLv3
  license_file: LICENSE
